# Generated by Django 5.1.6 on 2025-02-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs_wrkd_per_week', models.IntegerField()),
                ('tasks_completed', models.IntegerField()),
                ('sales_made', models.IntegerField()),
                ('productivity_score', models.FloatField(default=0.0)),
                ('error_rate', models.IntegerField()),
                ('customer_rating', models.FloatField()),
                ('returns_or_complaints', models.IntegerField()),
                ('quality_score', models.FloatField(default=0.0)),
                ('deadlines_met', models.IntegerField()),
                ('total_deadlines', models.IntegerField()),
                ('project_cmple_times', models.IntegerField()),
                ('target_cmple_times', models.IntegerField()),
                ('timeliness_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee', unique=True)),
            ],
            options={
                'db_table': 'employee_metrics',
            },
        ),
    ]
