# Generated by Django 5.1.6 on 2025-02-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employeemetrics_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
