# Generated by Django 5.1.6 on 2025-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_employee_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
